version: "3.8"

services:
  backend:
    build: ./backend
    container_name: ip-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ipdb

  frontend:
    build: ./frontend
    container_name: ip-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  mongo-data: