apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-backend
  template:
    metadata:
      labels:
        app: ip-backend
    spec:
      containers:
        - name: ip-backend
          image: ip-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/ipdb"
          resources:        # 
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ip-backend
spec:
  type: NodePort   # <--- Changed from ClusterIP
  selector:
    app: ip-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30081   # <--- Added this (port exposed on localhost)

