apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipreverser-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: ipreverser.local
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ipreverser-backend
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ipreverser-frontend
            port:
              number: 80
