apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  type: {{ .Values.mongo.service.type }}
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
    - name: mongo
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.containerPort }}
