apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongo.persistence.pvName }}
spec:
  capacity:
    storage: {{ .Values.mongo.persistence.storage | quote }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongo.persistence.storageClassName }}
  hostPath:
    path: {{ .Values.mongo.persistence.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.persistence.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.storage | quote }}
  storageClassName: {{ .Values.mongo.persistence.storageClassName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongo.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.name }}
    spec:
      containers:
        - name: {{ .Values.mongo.name }}
          image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.mongo.containerPort }}
          resources:
            requests:
              memory: {{ .Values.mongo.resources.requests.memory | quote }}
              cpu: {{ .Values.mongo.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.mongo.resources.limits.memory | quote }}
              cpu: {{ .Values.mongo.resources.limits.cpu | quote }}
          volumeMounts:
            - name: {{ .Values.mongo.name }}-data
              mountPath: /data/db
      volumes:
        - name: {{ .Values.mongo.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.persistence.pvcName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}-service
spec:
  selector:
    app: {{ .Values.mongo.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.containerPort }}
      targetPort: {{ .Values.mongo.containerPort }}