apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          imagePullPolicy: {{ .Values.mongo.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.mongo.containerPort }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.pvc.existingClaim | default "ipreverser-mongo-pvc" }}
